# disables non-TLS listeners, only TLS-enabled clients will be able to connect
listeners.tcp = none
listeners.ssl.default = 5671

ssl_options.certfile             = /etc/letsencrypt/live/amqp.albion-killbot.com/fullchain.pem
ssl_options.keyfile              = /etc/letsencrypt/live/amqp.albion-killbot.com/privkey.pem
# ssl_options.verify               = verify_peer
# ssl_options.fail_if_no_peer_cert = true

# management plugin
management.ssl.port       = 15671
management.ssl.certfile   = /etc/letsencrypt/live/amqp.albion-killbot.com/fullchain.pem
management.ssl.keyfile    = /etc/letsencrypt/live/amqp.albion-killbot.com/privkey.pem
