version: "3.9"

services:
  mongodb:
    image: mongo:5.0.8
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-config
        target: /data/configdb
    ports:
      - 27017:27017

  amqp:
    image: cloudamqp/lavinmq
    healthcheck:
      test: lavinmqctl status
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - type: volume
        source: amqp
        target: /var/lib/lavinmq
    ports:
      - 15672:15672
    expose:
      - 5672

  nginx:
    image: nginx:latest
    healthcheck:
      test: service nginx status || exit 1
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80

  stripe:
    image: stripe/stripe-cli:latest
    env_file:
      - ../server/.env
    entrypoint: sh -c 'stripe listen --forward-to http://api/subscriptions/stripe/webhook --api-key $$STRIPE_ACCESS_TOKEN'

  crawler:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: albion-killbot
    command: npm run start:crawler:dev
    depends_on:
      mongodb:
        condition: service_healthy
      amqp:
        condition: service_healthy
    env_file: ../server/.env
    environment:
      - NODE_ENV=development
      - AMQP_URL=amqp://amqp
      - MONGODB_URL=mongodb://mongodb:27017/albion-killbot
    volumes:
      - ../server/src:/app/src

  bot:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: albion-killbot
    command: npm run start:bot:dev
    depends_on:
      mongodb:
        condition: service_healthy
      amqp:
        condition: service_healthy
    env_file: ../server/.env
    environment:
      - NODE_ENV=development
      - AMQP_URL=amqp://amqp
      - MONGODB_URL=mongodb://mongodb:27017/albion-killbot
    volumes:
      - ../server/migrations:/app/migrations
      - ../server/bin:/app/bin
      - ../server/src:/app/src
      - type: volume
        source: cache
        target: /tmp/albion-killbot-cache

  api:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: albion-killbot
    command: npm run start:api:dev
    depends_on:
      mongodb:
        condition: service_healthy
      nginx:
        condition: service_started
      stripe:
        condition: service_started
    env_file: ../server/.env
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/albion-killbot
    volumes:
      - ../server/src:/app/src
      - type: volume
        source: cache
        target: /tmp/albion-killbot-cache
    expose:
      - 80

  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    image: albion-killbot-dashboard
    tty: true
    command: npm start
    depends_on:
      nginx:
        condition: service_started
    environment:
      - PORT=80
      - NODE_ENV=development
    volumes:
      - ../dashboard/public:/app/public
      - ../dashboard/src:/app/src
      - ../dashboard/tsconfig.json:/app/tsconfig.json
    expose:
      - 80

volumes:
  mongodb:
  mongodb-config:
  amqp:
  cache:
