version: "3.9"

services:
  mongodb:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-config
        target: /data/configdb
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    expose:
      - 5672

  crawler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run start:crawler:dev
    depends_on:
      - rabbitmq
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - "../bin:/app/bin"
      - "../src:/app/src"

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run start:bot:dev
    depends_on:
      - mongodb
      - rabbitmq
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/albion-killbot
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - "../bin:/app/bin"
      - "../src:/app/src"
      - type: volume
        source: cache
        target: /tmp/albion-killbot-cache

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run start:api:dev
    depends_on:
      - mongodb
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/albion-killbot
    volumes:
      - "../bin:/app/bin"
      - "../src:/app/src"
    ports:
      - 80:80

volumes:
  mongodb:
  mongodb-config:
  rabbitmq:
  cache:
